### ISSUE TITLE
Fix for Python 'def' keyword and arguments.

### ISSUE THREAD

**Issue by pbower** [gmr458/vscode_dark_modern.nvim#5]
Hi,

I'm wondering if you'd be happy to review the setup for Python for correctness, to help ensure the syntax presents correctly for VS Code ?

Currently:

- it shows the 'def' keyword in purple rather than blue when editing Python files.
- keyword arguments do not have any syntax highlighting applied, however it's light blue in vscode.
- there are a few smaller issues. E.g., 'for x in y' highlights for, but not 'in' with purple.

Thanks heaps!

Pete

**Comment by gmr458** [comment]
Hi, I was doing some tests and my conclusion is that maybe you are not using treesitter or you have it disabled.

This is Python code with treesitter highlighting:
![20240321_13h17m50s_grim](https://github.com/gmr458/vscode_modern_theme.nvim/assets/53343401/df585b60-ec17-4cf0-8ef9-ef981e5e65ea)

This is Python code without treesitter highlighting:
![20240321_13h21m37s_grim](https://github.com/gmr458/vscode_modern_theme.nvim/assets/53343401/01828d1b-222b-459f-8da7-1ca6f1b81a87)
